# Generated by Django 5.1.7 on 2025-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiverCompany_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Receiver_Address', models.CharField(max_length=100)),
                ('Receiver_City', models.CharField(max_length=30)),
                ('Receiver_GSTIN', models.CharField(max_length=100)),
                ('Receiver_State', models.CharField(max_length=100)),
                ('Receiver_Contact', models.CharField(max_length=30)),
                ('Receiver_Email', models.EmailField(max_length=100)),
                ('ModeOfTransport', models.CharField(blank=True, default='By Road', max_length=100, null=True)),
            ],
        ),
    ]
