# Generated by Django 5.1.7 on 2025-04-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverSide',
            fields=[
                ('ReceiverCompany_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Receiver_Address', models.CharField(max_length=100)),
                ('Receiver_City', models.CharField(max_length=30)),
                ('Receiver_GSTIN', models.CharField(max_length=100)),
                ('Receiver_State', models.CharField(max_length=100)),
                ('Receiver_Contact', models.CharField(max_length=30)),
                ('Receiver_Email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('ModeOfTransport', models.CharField(blank=True, default='By Road', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
