# Generated by Django 5.1.7 on 2025-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverside',
            name='ModeOfTransport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
