# Generated by Django 5.1.7 on 2025-04-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_rename_user_otp_user_rename_user_warehouse_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendersSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderCompany_Name', models.CharField(max_length=100)),
                ('Sender_Address', models.CharField(max_length=100)),
                ('Sender_City', models.CharField(max_length=30)),
                ('Sender_Email', models.EmailField(max_length=100)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductQuantity', models.IntegerField(blank=True, null=True)),
                ('Expected_Date', models.DateField(auto_now_add=True)),
                ('Warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.warehouse')),
            ],
        ),
    ]
