# Generated by Django 5.1.7 on 2025-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendersSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderCompany_Name', models.CharField(max_length=100)),
                ('Sender_Address', models.CharField(max_length=100)),
                ('Sender_City', models.CharField(max_length=30)),
                ('Sender_Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
