# Generated by Django 5.1.7 on 2025-04-03 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendersSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderCompany_Name', models.CharField(max_length=100)),
                ('Sender_Address', models.CharField(max_length=100)),
                ('Sender_City', models.CharField(max_length=30)),
                ('Sender_Email', models.EmailField(max_length=100)),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicebill')),
            ],
        ),
    ]
