# Generated by Django 5.1.7 on 2025-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendersside',
            name='Sender_Address',
            field=models.CharField(max_length=200),
        ),
    ]
