# Generated by Django 5.1.7 on 2025-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_sendersside_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendersside',
            name='Invoice',
        ),
    ]
