# Generated by Django 5.1.7 on 2025-04-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_alter_sendersside_sender_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendersside',
            name='Expected_Date',
        ),
        migrations.RemoveField(
            model_name='sendersside',
            name='ProductName',
        ),
        migrations.RemoveField(
            model_name='sendersside',
            name='ProductQuantity',
        ),
    ]
