# Generated by Django 5.1.7 on 2025-04-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_remove_sendersside_expected_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendersside',
            name='Expected_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sendersside',
            name='ProductName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendersside',
            name='ProductQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
