# Generated by Django 5.1.7 on 2025-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0005_remove_sendersside_warehouse_sendersside_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendersside',
            name='Sender_Address',
            field=models.CharField(max_length=500),
        ),
    ]
