# Generated by Django 5.1.7 on 2025-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarehouseCompany_Name', models.CharField(max_length=200)),
                ('WarehouseAddress', models.CharField(max_length=100)),
                ('WarehouseCity', models.CharField(max_length=30)),
                ('WarehouseGSTIN', models.CharField(max_length=100)),
                ('WarehouseState', models.CharField(max_length=100)),
                ('WarehousePincode', models.IntegerField()),
                ('WarehouseContact', models.CharField(max_length=30)),
                ('WarehouseEmail', models.EmailField(max_length=100)),
                ('WarehouseType', models.CharField(max_length=100)),
                ('WarehouseCapacity', models.IntegerField()),
                ('WarehouseAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
