# Generated by Django 5.1.7 on 2025-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_warehouse_warehousegstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='WarehousePincode',
            field=models.IntegerField(),
        ),
    ]
