# Generated by Django 5.1.7 on 2025-04-09 19:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_user_otp_user_rename_user_warehouse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, default='/default.jpg', max_length=255, null=True, verbose_name='document'),
        ),
    ]
