# Generated by Django 5.1.7 on 2025-04-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_warehouse_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='WarehouseAvailable',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='WarehouseCapacity',
        ),
    ]
