# Generated by Django 5.1.7 on 2025-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_warehouse_warehouseavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
