# Generated by Django 5.1.7 on 2025-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductQuantity', models.IntegerField()),
                ('ProductPrice', models.FloatField()),
                ('Product_Rejected', models.IntegerField()),
                ('Transaction_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=30)),
                ('ProductRestock', models.IntegerField()),
                ('ProductStatus', models.CharField(choices=[('available', 'Available'), ('Low', 'Low'), ('Replenished', 'Replenished')], default='Available', max_length=30)),
            ],
        ),
    ]
