# Generated by Django 5.1.7 on 2025-03-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductQuantity', models.IntegerField()),
                ('ProductPrice', models.FloatField()),
                ('Product_Rejected', models.IntegerField()),
                ('InBoundreadyProduct', models.IntegerField()),
                ('OutBoundreadyProduct', models.IntegerField()),
                ('Warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.warehouse')),
            ],
        ),
    ]
