# Generated by Django 5.1.7 on 2025-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ProductStatus',
            field=models.CharField(choices=[('InStock', 'InStock'), ('LowStock', 'LowStock'), ('OutofStock', 'OutofStock')], default='InStock', max_length=30),
        ),
    ]
