# Generated by Django 5.1.7 on 2025-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='Bill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
