# Generated by Django 5.1.7 on 2025-03-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_inventory_productstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ProductStatus',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ProductRestock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
