# Generated by Django 5.1.7 on 2025-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('InStock', 'In Stock'), ('LowStock', 'Low Stock'), ('OutofStock', 'Out of Stock')], default='InStock', max_length=20),
        ),
    ]
