# Generated by Django 5.1.7 on 2025-04-14 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound', '0006_alter_sendersside_sender_address'),
        ('outbound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.CharField(max_length=100, unique=True)),
                ('Bill_date', models.DateField(auto_now_add=True)),
                ('Bill_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Bill_time', models.DateTimeField(auto_now=True)),
                ('Bill_validity', models.DateField()),
                ('ValueOfGoods', models.IntegerField(default=0)),
                ('ReasonForTransport', models.TextField()),
                ('CEWBno', models.IntegerField()),
                ('MultiVehInfo', models.IntegerField()),
                ('Bill_pdf', models.URLField(blank=True, null=True)),
                ('Sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.sendersside')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outbound.receiverside')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
