# Generated by Django 5.1.7 on 2025-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebill',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='invoicebill',
            name='Transporter',
        ),
        migrations.RemoveField(
            model_name='invoicebill',
            name='Warehouse',
        ),
    ]
