# Generated by Django 5.1.7 on 2025-03-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='Bill_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
