# Generated by Django 5.1.7 on 2025-04-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
        ('invoice', '0002_remove_invoicebill_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='Sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.sendersside'),
        ),
    ]
