# Generated by Django 5.1.7 on 2025-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoicebill_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='Bill_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
