# Generated by Django 5.1.7 on 2025-04-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoicebill_bill_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='Bill_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='Invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
