# Generated by Django 5.1.7 on 2025-03-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransporterName', models.CharField(blank=True, max_length=100, null=True)),
                ('TransporterAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Transporter_Contact', models.CharField(max_length=30)),
                ('Transporter_Email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(max_length=100)),
                ('Driver_Contact', models.CharField(max_length=20)),
                ('Driver_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Vehicle_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Driver_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transporter')),
            ],
        ),
    ]
