# Generated by Django 5.1.7 on 2025-04-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transporter_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Driver_Location',
        ),
        migrations.CreateModel(
            name='Driver_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.driver')),
            ],
        ),
    ]
